{% set name = "maggma" %}
{% set version = "0.30.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/maggma-{{ version }}.tar.gz
  sha256: 1e2bcf12bd9ec707c98463b855ce969d99625bbeed4246a74cd49f4f3737b8e4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools_scm
    - python >=3.7
  run:
    - aioitertools >=0.5.1
    - dnspython >=1.16.0
    - fastapi >=0.42.0
    - jsonschema >=3.1.1
    - mongogrant >=0.3.1
    - mongomock >=3.10.0
    - monty >=1.0.2
    - msgpack-python >=0.5.6
    - numpy >=1.17.3
    - pydantic >=0.32.2
    - pydash >=4.1.0
    - pymongo >=3.6
    - pynng >=0.5.0
    - python >=3.7
    - setuptools
    - sshtunnel >=0.1.5
    - tqdm >=4.19.6

test:
  imports:
    - maggma
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://materialsproject.github.io/maggma/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: MongoDB aggregation machine
  description: |
    Maggma is a framework to build data pipelines from files on disk all 
    the way to a REST API in scientific environments. Maggma has been 
    developed by the Materials Project (MP) team at Lawrence Berkeley 
    Labs.
  doc_url: https://materialsproject.github.io/maggma/
  dev_url: https://github.com/materialsproject/maggma

extra:
  recipe-maintainers:
    - jan-janssen
