{% set name = "maggma" %}
{% set version = "0.72.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/maggma-{{ version }}.tar.gz
  sha256: 929ea18ae92e1b91480541af84a36bca2c817e36483c6eae874438a2d523bd38

build:
  entry_points:
    - mrun = maggma.cli:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=5
    - pip
  run:
    - paramiko <4
    - jsonlines >=4.0.0
    - pandas >=2.2
    - python >={{ python_min }}
    - setuptools
    - ruamel.yaml >=0.17
    - pydantic >=2.0
    - pydantic-settings >=2.0.3
    - pymongo >=4.2.0,<4.11
    - monty >=2024.5.24
    - mongomock >=3.10.0
    - pydash >=4.1.0
    - jsonschema >=3.1.1
    - tqdm >=4.19.6
    - mongogrant >=0.3.1
    - aioitertools >=0.5.1
    - numpy >=1.26
    - fastapi >=0.42.0
    - pyzmq >=25.1.1
    - dnspython >=1.16.0
    - sshtunnel >=0.1.5
    - msgpack-python >=0.5.6
    - orjson >=3.9.0
    - boto3 >=1.20.41
    - python-dateutil >=2.8.2
    - uvicorn >=0.18.3

test:
  imports:
    - maggma
  commands:
    - pip check
    - mrun --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/maggma
  summary: Framework to develop datapipelines from files on disk to full dissemenation API
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
